version: '3.9'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - .db/:/data/db
    env_file:
      - .env
  server:
    network_mode: host
    build: .
    command: ["autoguard"]
    env_file:
      - .env
    depends_on:
      - mongodb


